apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: ooptyp/online_inference:v2
      name: online-inference

      ports:
      - name: probe-port
        containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

      readinessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 5

      livenessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 50
        periodSeconds: 10
